# Table of contents:
# 1: Poutine component merging
# 2: Large-Small Boulder support for Cloud 9

[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# == 1: Allows Poutine components to bypass Joker slot limits given other components are present
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "not (card.ability.set == 'Joker' and #G.jokers.cards < G.jokers.config.card_limit + ((card.edition and card.edition.negative) and 1 or 0)) and"
position = "after"
payload = '''
not (card.label == "j_tiwmig_french_fries" and#G.jokers.cards >= G.jokers.config.card_limit and (
    #SMODS.find_card("j_tiwmig_gravy") > 0 or
    #SMODS.find_card("j_tiwmig_cheese_curds") > 0 or
    #SMODS.find_card("j_tiwmig_cheesy_gravy") > 0
)) and
not (card.label == "j_tiwmig_gravy" and #G.jokers.cards >= G.jokers.config.card_limit and (
    #SMODS.find_card("j_tiwmig_cheese_curds") > 0 or
    #SMODS.find_card("j_tiwmig_french_fries") > 0 or
    #SMODS.find_card("j_tiwmig_chips_n_cheese") > 0
)) and
not (card.label == "j_tiwmig_cheese_curds" and #G.jokers.cards >= G.jokers.config.card_limit and (
    #SMODS.find_card("j_tiwmig_french_fries") > 0 or
    #SMODS.find_card("j_tiwmig_gravy") > 0 or
    #SMODS.find_card("j_tiwmig_frite_sauce") > 0
)) and
'''
match_indent = true

# == 2: Large-Small Boulder support for Cloud 9
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if v:get_id() == 9 then self.ability.nine_tally = self.ability.nine_tally+1 end"
position = "after"
payload = """if v:get_id() == 8 and #SMODS.find_card("j_tiwmig_large_small_boulder") > 0 then self.ability.nine_tally = self.ability.nine_tally+1 end"""
match_indent = true