[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# function Card:update
# Large-Small Boulder support for Cloud 9
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if v:get_id() == 9 then self.ability.nine_tally = self.ability.nine_tally+1 end"
position = "after"
payload = """if v:get_id() == 8 and #SMODS.find_card("j_tiwmig_large_small_boulder") > 0 then self.ability.nine_tally = self.ability.nine_tally+1 end"""
match_indent = true